openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/category/:
    get:
      operationId: listCategoryCreates
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/category/{id}/:
    get:
      operationId: retrieveCategoryRetrieveUpdateDestroy
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    put:
      operationId: updateCategoryRetrieveUpdateDestroy
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCategoryRetrieveUpdate
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/product/:
    get:
      operationId: listProducts
      description: ''
      parameters:
      - name: brend
        required: false
        in: query
        description: brend
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
    post:
      operationId: createProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
  /api/v1/product/{id}/:
    get:
      operationId: retrieveProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
    put:
      operationId: updateProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/brend/:
    get:
      operationId: listBrends
      description: ''
      parameters:
      - name: title
        required: false
        in: query
        description: title
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brend'
          description: ''
      tags:
      - api
    post:
      operationId: createBrend
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Brend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Brend'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Brend'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brend'
          description: ''
      tags:
      - api
  /api/v1/brend/{id}/:
    get:
      operationId: retrieveBrend
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this brend.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brend'
          description: ''
      tags:
      - api
    put:
      operationId: updateBrend
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this brend.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Brend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Brend'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Brend'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brend'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateBrend
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this brend.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Brend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Brend'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Brend'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brend'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyBrend
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this brend.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
        desc:
          type: string
          nullable: true
        image:
          type: string
          format: binary
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000000
          minimum: -100000000
        rating:
          type: integer
          maximum: 10
          minimum: 0
        cat_id:
          type: string
          readOnly: true
        brend:
          type: string
          readOnly: true
      required:
      - title
      - image
      - price
      - rating
    Brend:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
      required:
      - title
